//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1 {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2022 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class formListaUsuarios {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("WindowsFormsApp1.formListaUsuarios", typeof(formListaUsuarios).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a resource 'apellido.UserAddedColumn'.
        /// </summary>
        public static bool apellido_UserAddedColumn {
            get {
                return ((bool)(ResourceManager.GetObject(ResourceNames.apellido_UserAddedColumn, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'direccion.UserAddedColumn'.
        /// </summary>
        public static bool direccion_UserAddedColumn {
            get {
                return ((bool)(ResourceManager.GetObject(ResourceNames.direccion_UserAddedColumn, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'fecha_nac.UserAddedColumn'.
        /// </summary>
        public static bool fecha_nac_UserAddedColumn {
            get {
                return ((bool)(ResourceManager.GetObject(ResourceNames.fecha_nac_UserAddedColumn, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'nombre.UserAddedColumn'.
        /// </summary>
        public static bool nombre_UserAddedColumn {
            get {
                return ((bool)(ResourceManager.GetObject(ResourceNames.nombre_UserAddedColumn, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'apellido.UserAddedColumn'.
            /// </summary>
            public const string apellido_UserAddedColumn = "apellido.UserAddedColumn";
            
            /// <summary>
            /// Stores the resource name 'direccion.UserAddedColumn'.
            /// </summary>
            public const string direccion_UserAddedColumn = "direccion.UserAddedColumn";
            
            /// <summary>
            /// Stores the resource name 'fecha_nac.UserAddedColumn'.
            /// </summary>
            public const string fecha_nac_UserAddedColumn = "fecha_nac.UserAddedColumn";
            
            /// <summary>
            /// Stores the resource name 'nombre.UserAddedColumn'.
            /// </summary>
            public const string nombre_UserAddedColumn = "nombre.UserAddedColumn";
        }
    }
}
